apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeatconf
data:
  filebeat.yml: |-
    filebeat.inputs:
    - input_type: log
      paths:
        - /data/log/*/*.log
      tail_files: true
      fields:
        pod_name: '${podName}'
        pod_ip: '${podIp}'
        pod_deploy_name: '${podDeployName}'
        pod_namespace: '${podNamespace}'
    setup.template.name: "filebeat-sidecar"
    setup.template.pattern: "filebeat-sidecar-*"
    output.elasticsearch:
      hosts: ["es-filebeat.logging:9200"]
      index: "filebeat-sidecar-%{+yyyy.MM}"
